---

- name: APT - Install packages
  apt:
    state: latest
    name: "{{ apt_install_packages }}"
  when: apt_install_packages

- name: APT - Remove packages
  apt:
    state: absent
    name: "{{ apt_remove_packages }}"
  when: apt_remove_packages

- name: APT - Full system update
  apt:
    upgrade: full
  tags:
    - full-update

- name: Rebooting if needed...
  command: shutdown -r now removes=/var/run/reboot-required
  async: 0
  poll: 0
  ignore_errors: true
  register: restarted
  tags:
    - full-update

- name: Wait for SSH to come up {{ host_ip }}
  wait_for_connection:
      timeout: 300
