---
- name: APT - Install packages
  ansible.builtin.apt:
    state: present
    name: "{{ apt_install_packages }}"
  when: apt_install_packages

- name: APT - Remove packages
  ansible.builtin.apt:
    state: absent
    name: "{{ apt_remove_packages }}"
  when: apt_remove_packages

- name: APT - Full system update
  ansible.builtin.apt:
    upgrade: full
  tags:
    - full-update

- name: Rebooting if needed...
  ansible.builtin.command:
    cmd: shutdown -r now
    removes: /var/run/reboot-required
  async: 0

- name: Wait for SSH to come up {{ host_ip }}
  ansible.builtin.wait_for_connection:
    timeout: 300
