---

- name: Launch Chromium on Start Task1
  lineinfile: dest=/home/{{ user_name }}/.config/lxsession/LXDE-pi/autostart
              line="@/usr/bin/chromium-browser --start-fullscreen --incognito "{{ dashboard_url }}""
  become: True
  become_method: sudo

- name: Launch Chromium on Start Task2
  lineinfile: dest=/home/{{ user_name }}/.config/lxsession/LXDE-pi/autostart
              line="@/usr/bin/xdotool x y"
  become: True
  become_method: sudo

- name: restart server
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  become: yes
  become_method: sudo
  ignore_errors: true

- name: Wait for SSH to come up {{ ansible_ssh_host }}
  local_action:
    wait_for
      port=22
      host={{ host_ip }}
      search_regex=OpenSSH
      delay=30
      timeout=300
      connect_timeout=15
  sudo: false
