---
- name: Launch Chromium on Start Task1
  ansible.builtin.lineinfile:
    dest: /home/{{ user_name }}/.config/lxsession/LXDE-pi/autostart
    state: present
    line: "@/usr/bin/chromium-browser --start-fullscreen --incognito {{ dashboard_url }}"
  become: true
  become_method: ansible.builtin.sudo

- name: Launch Chromium on Start Task2
  ansible.builtin.lineinfile:
    dest: /home/{{ user_name }}/.config/lxsession/LXDE-pi/autostart
    state: present
    line: "@/usr/bin/xdotool x y"
  become: true
  become_method: ansible.builtin.sudo

- name: Restart server
  ansible.builtin.reboot:
    msg: "Rebooting after Chromium configuration"
    connect_timeout: 5
    pre_reboot_delay: 2
  async: 1
  poll: 0
  become: true
  become_method: ansible.builtin.sudo
  failed_when: false

- name: Wait for SSH to come up {{ host_ip }}
  ansible.builtin.wait_for_connection:
    delay: 60
    timeout: 300
