---
- name: Include vars of all.yml.
  ansible.builtin.include_vars:
    file: all.yml

- name: Include vars of secrets.yml.
  ansible.builtin.include_vars:
    file: secrets.yml

- name: Include config tasks
  ansible.builtin.include_tasks: config.yml

- name: Include SSH tasks
  ansible.builtin.include_tasks: ssh.yml

- name: Include APT tasks
  ansible.builtin.include_tasks: apt.yml

- name: Include user tasks
  ansible.builtin.include_tasks: user.yml

- name: Include Chromium tasks
  ansible.builtin.include_tasks: chromium.yml
