---

- name: Remove Root SSH Configuration
  file: path=/root/.ssh state=absent

- name: Disable Challenge Response Authentication
  lineinfile: dest=/etc/ssh/sshd_config
              state=present
              regexp="^ChallengeResponseAuthentication"
              line="ChallengeResponseAuthentication no"
  become: True
  notify: restart ssh

- name: Update sshd_config Parameters
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    insertafter: EOF
  with_items:
    - { key: 'PermitRootLogin', value: 'no' }
    - { key: 'LoginGraceTime', value: '20' }
    - { key: 'X11Forwarding', value: 'no' }
    - { key: 'ClientAliveInterval', value: '30' }
    - { key: 'ClientAliveCountMax', value: '1000' }
  notify:
    - restart ssh
